### ISSUE TITLE
How about zendframework/zend-resources

### ISSUE THREAD

**Issue by samsonasik** [zendframework/component-split#14]
Is it need to be splitted too ?

**Comment by samsonasik** [comment]
for additional note, zendframework/zend-resources is not in packagist nore in packages.zendframework.com yet

**Comment by weierophinney** [comment]
We never created a package for it. I'll add it to my to-do; it needs to be addressed in a slightly different way than the components. Consumers will be needing to pass the path to the resources when consuming them via `Zend\I18n`, which will require some code to return that path.

**Comment by Maks3w** [comment]
Related https://github.com/zendframework/zf2/issues/6642

**Comment by Maks3w** [comment]
Resources has been published with the name `zendframework/zend-i18n-resources`

**Comment by weierophinney** [comment]
Which is here: https://github.com/zendframework/zend-i18n-resources - and it's on both packagist and packages.zendframework.com.
