### ISSUE TITLE
History is duplicated master branch and tags have duplicated commits

### ISSUE THREAD

**Issue by Maks3w** [zendframework/component-split#29]
![image](https://cloud.githubusercontent.com/assets/1301698/7766262/c15b860e-0067-11e5-837b-1b4ae289c773.png)

Master branch and 2.4.\* tags share the same contents but they are different trees

For ex: `[2.4.2] Release readiness is duplicated in both trees`

https://github.com/zendframework/zend-version/commit/4ac7fbaa275f52d070d213fd8461ee17a3589748 2.4.2 Tag

https://github.com/zendframework/zend-version/commit/d59789c26a950fff70ad8b0a7a1fa96b1dd356b2 Master branch

Options:
- Hard reset master HEAD to match 2.4.2 commit
  
  Pro: Simple to do  and master branch is not stable so rewrite history is not a BC break
  Con: Latest commit in master will be lost (bump to 2.4.3-dev), however this version is not in the roadmap

or
- Rewrite tags and match a master commit
  
  Pro: Git history will be smaller. This tree has more empty commits than master
  Con: Require to change "stable" tags references

**Comment by Maks3w** [comment]
Result after hard reset master HEAD to match 2.4.2 commit

![image](https://cloud.githubusercontent.com/assets/1301698/7766412/50c69210-0069-11e5-8787-e0ac4e2d8273.png)

**Comment by Maks3w** [comment]
Result after rewrite tags

![image](https://cloud.githubusercontent.com/assets/1301698/7766495/fdc476f8-0069-11e5-81ac-a0b9218046c3.png)

**Comment by weierophinney** [comment]
Rewriting the tags at this point is not reasonable, as it breaks current installs.

In terms of having duplicate trees, that makes sense; I branch to prep the tree for release readiness, and what you're seeing is that branch. I'm really not sure we need to do anything more at this point.

**Comment by Maks3w** [comment]
Just changing the reference of master we can safely drop a tree

**Comment by Maks3w** [comment]
> (18:05:24) weierophinney: Maks3w: if you can do so without rewriting tag references, go for it. However, take a look and make sure none of them have new commits; I think some have gone through in the past 24 hours.

**Comment by Maks3w** [comment]
> $ for i in $(ls -d zend*); do (cd $i; git push -f origin master); done
> Total 0 (delta 0), reused 0 (delta 0)
> To git@github.com:zendframework/zend-authentication.git
> - 8cc832a...6868e48 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-barcode.git
> - 06ab2de...84ba1b0 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-cache.git
> - aabea80...e75d3fb master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-captcha.git
> - 88b8317...8b2d22b master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-code.git
> - 94a7a3b...e3b32fa master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-config.git
> - 401cb1c...6b879e5 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-console.git
> - 61b29f1...92f9c51 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-crypt.git
> - d4f2ad4...ec78d08 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-db.git
> - 7f6beab...b78b12c master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-debug.git
> - 93c6d77...21bc83e master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-di.git
> - 86b5171...fb578aa master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-dom.git
> - 76ed64b...445aefb master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-escaper.git
> - 84e0c15...13f468f master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-eventmanager.git
> - b7bc0ff...c2c46a7 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-feed.git
> - 9e4804a...5bec1d5 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-file.git
> - d536276...eafa689 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-filter.git
> - fbf4839...a371110 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-form.git
> - d8514f6...d4719b4 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-http.git
> - fdaad7e...0d1bbff master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-i18n.git
> - 2663502...f26d6ae master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-inputfilter.git
> - b912732...31c7370 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-json.git
> - 3fc8820...1db4b87 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-ldap.git
> - 90cb2d9...07bfa76 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-loader.git
> - a91f460...5e62c44 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-log.git
> - 2f72d03...f6538f4 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-mail.git
> - ea143e3...0d4f368 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-math.git
> - 63c9021...1e7e803 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-memory.git
> - 3bc263f...45f0e60 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-mime.git
> - e1acb22...df81ca9 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-modulemanager.git
> - c7ac34d...49c0713 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-mvc.git
> - 880ca2c...680cf79 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-navigation.git
> - 44659b7...2753d71 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-paginator.git
> - ec8782d...4e58de6 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-permissions-acl.git
> - 80ee225...695abe7 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-permissions-rbac.git
> - 82fbcd1...1393424 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-progressbar.git
> - 778824e...25ff6de master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-serializer.git
> - bb0cb07...31a0da5 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-server.git
> - 866e86e...dd6da0d master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-servicemanager.git
> - 9d9b06e...855294e master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-session.git
> - 7ce6c3e...da7f574 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-soap.git
> - e8387f6...743ab44 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-stdlib.git
> - e8d0fe5...a5dd7fd master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-tag.git
> - 5d1898a...13d3b1d master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-test.git
> - cff4c86...f743e5f master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-text.git
> - 4444219...bd2393f master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-uri.git
> - 014f814...180b747 master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-validator.git
> - bffb40d...43a3042 master -> master (forced update)
>   Counting objects: 4, done.
>   Delta compression using up to 8 threads.
>   Compressing objects: 100% (3/3), done.
>   Writing objects: 100% (4/4), 411 bytes | 0 bytes/s, done.
>   Total 4 (delta 2), reused 1 (delta 0)
>   To git@github.com:zendframework/zend-version.git
> - 6277154...28a1c6f master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-view.git
> - f71175d...72a675d master -> master (forced update)
>   Total 0 (delta 0), reused 0 (delta 0)
>   To git@github.com:zendframework/zend-xmlrpc.git
> - 210bbfc...5a3cf68 master -> master (forced update)
