### ISSUE TITLE
[Split] PHP CS Fixer

### ISSUE THREAD

**Issue by Maks3w** [zendframework/component-split#7]
_From @gianarb on April 1, 2015 23:36_

Hi!
In your opinion current flow of cs-fix's check  is good??
In my opinion this check is not on the same level of the tests failure.

I'm follow this project [StyleCI - code](https://github.com/StyleCI/StyleCI) || [StyleCI - service](https://styleci.io/) this is a good idea for a lot of reasons.
- Centralize configuration.. We can manage change of config for all components from single point.
- We can do a different signal if a build failure because a tests is broken or because there is a problem of code style..

In my opinion if I know which PRs don't follow a standard code I can merge them anyway and after a lot of merge I can run CS-fix

_Copied from original issue: zendframework/zf2#7402_

**Comment by Maks3w** [comment]
_From @samsonasik on April 2, 2015 6:10_

I'm :+1: for it. We can eliminate the .php_cs and php-cs-fixer call in .travis.yml then, right?

**Comment by Maks3w** [comment]
_From @samsonasik on April 2, 2015 6:13_

the drawback for it is we still can't exclude folder based on this discussion https://blog.styleci.io/redefining-configuration/#comment-1922515343

**Comment by Maks3w** [comment]
_From @gianarb on April 2, 2015 7:25_

Yes but in my opinion this proposal would become more specific, maybe we can extends this flow for other check.. Orchestration of components for the future is a very interesting argument

**Comment by Maks3w** [comment]
The requirements for the CS tool are two.
- Alert from CS violations
- Provide fix for the CS violation

We want a tool which help the developer to fix the CS violations.

**Comment by Maks3w** [comment]
_From @gianarb on April 2, 2015 9:43_

If you are one or more important PRs maybe you can merge a lot of them and
after this process you can apply a CS fix..
I don't know in my opinion this type of check require a different signal :)
But it's my opinion

**Comment by Maks3w** [comment]
_From @gianarb on April 2, 2015 10:41_

StyleCI or other server-ci is a very big step maybe in this moment it's too demanding but we can starting from zendframework/coding-standard project to centralize configuration

[see doctrine](https://github.com/doctrine/coding-standard)

**Comment by weierophinney** [comment]
@Maks3w The nice part about `php-cs-fixer` and `phpcs` is that they each include tools that allow the developer to _fix_ the majority of problems. This means that they can proactively use the tool to ensure the build passes, or, after a failed build, run the tool to correct the issues.

My personal preference is phpcs, as it covers the entire spectrum of PSR-1 and PSR-2, as well as has relatively easy methods for customizing sniffs. However, the php-cs-fixer lead has been very pro-active in assisting with our project, which has been the deciding factor so far in the use of that particular tool.

We can re-evaluate which tool we'll use after the components are split.
